services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  cache:
    ports:
      - "6379:6379"

  fileserver:
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
