services:
  db:
    image: postgres:14.5
    ports:
      - "5432"

  cache:
    image: redis:7
    ports:
      - "6379"

  fileserver:
    build: .
    ports:
      - "8080"
    depends_on:
      - db
      - cache
