version: "3"

services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  cache:
    image: redis:7
    ports:
      - "6379:6379"

  fileserver:
    build: .
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
